import {
  boolean,
  index,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { organizations } from './org';
import { aiRuns } from './observability';
import { nicheTargetSourceEnum } from './enums';

// Shared niche vocabulary linking campaigns and MANUAL leads. `slug` is the
// lower/trim dedup key (the unique constraint), `name` keeps the display
// casing. Rows are find-or-created from the AIM campaign form.
export const niches = pgTable(
  'niches',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // Tenant boundary. NOT NULL: every niche belongs to exactly one org.
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex('niches_organization_id_slug_uq').on(t.organizationId, t.slug),
    index('niches_organization_id_idx').on(t.organizationId),
  ],
);

// Target archetypes a niche expands into ("Cloud Infrastructure" → provider,
// installer, MSP, …). AI-generated by the NICHE ANALYTICS workflow on a niche's
// first use; human-editable afterwards (rename, disable, add MANUAL rows).
// Tenancy is inherited via the parent niche (nicheTargets.nicheId); no own
// organizationId column.
export const nicheTargets = pgTable(
  'niche_targets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    nicheId: uuid('niche_id')
      .notNull()
      .references(() => niches.id),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    // Optional query hint Lead Satellite appends when hunting this archetype.
    searchHint: text('search_hint'),
    source: nicheTargetSourceEnum('source').notNull().default('AI'),
    // Disabled targets are kept (evidence) but skipped by Lead Satellite.
    enabled: boolean('enabled').notNull().default(true),
    // The AI run that generated this target (null for MANUAL rows).
    aiRunId: uuid('ai_run_id').references(() => aiRuns.id),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [uniqueIndex('niche_targets_niche_id_slug_uq').on(t.nicheId, t.slug)],
);
