import type {
  Campaign,
  CampaignEmail,
  Lead,
  SenderSchedule,
} from './types';

export const REACH_CAMPAIGNS: Campaign[] = [
  {
    id: 'wohnbau',
    name: 'Housing Co-ops ≥ 500 units',
    niche: 'Housing',
    region: 'Bavaria',
    companies: 96,
    status: 'NEW',
  },
  {
    id: 'hv',
    name: 'Property Mgmt Firms (Metro)',
    niche: 'Property Mgmt',
    region: 'NRW',
    companies: 118,
    status: 'IN CAMPAIGN',
  },
  {
    id: 'kommune',
    name: 'Municipal Utilities w/ Housing Arm',
    niche: 'Municipality',
    region: 'DE',
    companies: 72,
    status: 'IN CAMPAIGN',
  },
  {
    id: 'installateur',
    name: 'Installers (Resale)',
    niche: 'Installer',
    region: 'DE-South',
    companies: 84,
    status: 'OVER',
  },
  {
    id: 'fm',
    name: 'Facility Management Groups',
    niche: 'Property Mgmt',
    region: 'Bavaria',
    companies: 102,
    status: 'IN CAMPAIGN',
  },
  {
    id: 'wholesale',
    name: 'Electrical Wholesalers',
    niche: 'Wholesale',
    region: 'NRW',
    companies: 88,
    status: 'OVER',
  },
];

export const REACH_LEADS: Record<string, Lead[]> = {
  wohnbau: [
    {
      id: 'l1',
      company: 'Munich Housing Co-op',
      contact: 'Mr. Brandl · Board',
      location: 'Munich',
      source: 'iBau',
      status: 'New',
    },
    {
      id: 'l2',
      company: 'Augsburg Building Society',
      contact: 'Ms. Keller · Portfolio',
      location: 'Augsburg',
      source: 'Company DB',
      status: 'New',
    },
    {
      id: 'l3',
      company: 'Nuremberg Living Spaces GmbH',
      contact: 'Mr. Maier · Purchasing',
      location: 'Nuremberg',
      source: 'Company DB',
      status: 'New',
    },
  ],
  hv: [
    {
      id: 'l4',
      company: 'HV Rheinland GmbH',
      contact: 'Mr. Schmitz · Portfolio',
      location: 'Cologne',
      source: 'Company DB',
      status: 'Interested',
    },
    {
      id: 'l5',
      company: 'ProImmo Mgmt',
      contact: 'Ms. Wagner · Asset Management',
      location: 'Düsseldorf',
      source: 'Company DB',
      status: 'Unsure',
    },
    {
      id: 'l6',
      company: 'Verwaltung Ruhr24',
      contact: 'Ms. Yilmaz · Office',
      location: 'Essen',
      source: 'Company DB',
      status: 'Not Interested',
    },
  ],
};

export const REACH_EMAILS: Record<string, CampaignEmail[]> = {
  wohnbau: [
    {
      id: 'e1',
      step: 'Cold Outreach',
      round: 'Round 1',
      subject: '600W balcony solar kits for your units - tiered pricing',
      status: 'DRAFT',
      sent: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      bounced: 0,
      meetings: 0,
    },
    {
      id: 'e2',
      step: 'Follow Up',
      round: 'Round 2',
      subject: 'Following up - tiered pricing and delivery times',
      status: 'DRAFT',
      sent: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      bounced: 0,
      meetings: 0,
    },
    {
      id: 'e3',
      step: 'Final Push',
      round: 'Round 3',
      subject: 'Last note before I close your file',
      status: 'DRAFT',
      sent: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      bounced: 0,
      meetings: 0,
    },
  ],
  hv: [
    {
      id: 'e4',
      step: 'Cold Outreach',
      round: 'Round 1',
      subject: '600W balcony solar kits for your units - tiered pricing',
      status: 'SENT',
      sent: 118,
      opened: 64,
      clicked: 13,
      replied: 10,
      bounced: 3,
      meetings: 3,
    },
    {
      id: 'e5',
      step: 'Follow Up',
      round: 'Round 2',
      subject: 'Following up - tiered pricing and delivery times',
      status: 'SENT',
      sent: 101,
      opened: 46,
      clicked: 8,
      replied: 6,
      bounced: 1,
      meetings: 1,
    },
    {
      id: 'e6',
      step: 'Final Push',
      round: 'Round 3',
      subject: 'Last note before I close your file',
      status: 'SCHEDULED',
      sent: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      bounced: 0,
      meetings: 0,
    },
  ],
};

export const SENDER_SCHEDULE: SenderSchedule[] = [
  {
    id: 's1',
    campaign: 'Housing Co-ops ≥ 500 units',
    nicheRegion: 'Housing · BY',
    round: '0 / 3',
    nextSend: 'Tomorrow 09:00',
    status: 'NEW',
  },
  {
    id: 's2',
    campaign: 'Property Mgmt Firms (Metro)',
    nicheRegion: 'Property Mgmt · NRW',
    round: '2 / 3',
    nextSend: 'Thu 09:00',
    status: 'FOLLOWED UP',
  },
  {
    id: 's3',
    campaign: 'Municipal Utilities w/ Housing Arm',
    nicheRegion: 'Municipality · DE',
    round: '2 / 3',
    nextSend: 'Fri 09:00',
    status: 'FOLLOWED UP',
  },
  {
    id: 's4',
    campaign: 'Installers (Resale)',
    nicheRegion: 'Installer · DE-South',
    round: '3 / 3',
    nextSend: '-',
    status: 'OVER',
  },
];

export const DAILY_SENDS = [
  { date: '9/6', value: 88, type: 'past' },
  { date: '10/6', value: 96, type: 'past' },
  { date: '11/6', value: 84, type: 'past' },
  { date: '12/6', value: 110, type: 'past' },
  { date: '13/6', value: 102, type: 'past' },
  { date: '16/6', value: 118, type: 'past' },
  { date: 'Today', value: 88, type: 'today' },
  { date: '18/6', value: 104, type: 'future' },
  { date: '19/6', value: 96, type: 'future' },
  { date: '20/6', value: 82, type: 'future' },
];